export const EMPLOYEES_DELETE_EMPLOYEE = 'EMPLOYEES_DELETE_EMPLOYEE';
export const EMPLOYEES_CREATE_EMPLOYEE = 'EMPLOYEES_CREATE_EMPLOYEE';
export const EMPLOYEES_UPDATE_EMPLOYEE = 'EMPLOYEES_UPDATE_EMPLOYEE';
