// ACTION VERBS
export const ON_AUTH_STATE_CHANGE = 'ON_AUTH_STATE_CHANGE';

// GETTERS
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';

export const AUTH_VERIFY_USER_TOKEN = 'AUTH_VERIFY_USER_TOKEN';
export const AUTH_DELETE_USER_TOKEN = 'AUTH_DELETE_USER_TOKEN';
export const AUTH_SET_USER_TOKEN = 'AUTH_SET_USER_TOKEN';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
